### ISSUE TITLE
0x10a7c364f25d8a83ff1d5b8db31c7ec54bb64b12
Abdulhafez 0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328
bdalhafzslah382@gmail.com 

### ISSUE THREAD

**Issue by Chator1** [web3/web3.js#7308]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by danforbes** [comment]
I think this Issue may have been created in error. If you have a question please open a new Issue.

**Comment by Chator1** [comment]
Add coins to my Binance wallet[0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328]
